### ISSUE TITLE
TagControllerImpl: Code Review

### ISSUE THREAD

**Issue by mccollum3d** [revaturelabs/cms-backend#7]
```java
@RestController
@RequestMapping(produces = {MediaType.APPLICATION_JSON_VALUE})
```

- Change to @RestController("tagController") to be consistent with the other 2 controllers (who explicitly name their controllers)

- Change to @RequestMapping(value="/tags")
```java
@GetMapping("/tags")
    public List<Tag> getAllTags() {
        return tagService.getAllTags();
    }
```

- This method dead-ends in the service layer returning an empty List. Create a query in the Repo.

- Change to @GetMapping("/getall")

```java
    @GetMapping("/tags/{tagId}")
 @DeleteMapping("/tags/{tagId}")
```

- remove the /tags from the start of the mapping, and either leave as /{tagId} or rename to appropriate uris such as /get/{tagId} or /delete/{tagId}

```java
@PostMapping("/tags")
```

- Change to "/create" (so it'll be /tags/create when combined with the @RequestMapping

**Comment by nateman9001** [comment]
Issues should be fixed.

**Comment by PiedPiper11** [comment]
Tag controller naming up to date. Still having issue when testing delete request

**Comment by nateman9001** [comment]
Yea I think that get messed up in Git.
